<div class="carousel-wrap">
  <div class="owl-carousel">
	<div class="item"><img src=></div>
	<div class="item"><img src="https://m.media-amazon.com/images/I/81oUvlsYcnL._SL1500_.jpg"></div>
	<div class="item"><img src="https://m.media-amazon.com/images/I/81lmkcoo76L._UL1400_.jpg"></div>
	<div class="item"><img src="https://images.unsplash.com/photo-1584917865442-de89df76afd3?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8YmFnfGVufDB8fDB8fA%3D%3D&w=1000&q=80"></div>
	<div class="item"><img src="https://m.media-amazon.com/images/I/81IiFRUxeWL._UY550_.jpg"></div>
	<div class="item"><img src="https://images.unsplash.com/photo-1622560480654-d96214fdc887?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8c2Nob29sJTIwYmFnfGVufDB8fDB8fA%3D%3D&w=1000&q=80"></div>
	<div class="item"><img src="https://5.imimg.com/data5/CC/JL/MY-29211282/designer-school-bag-500x500.jpg"></div>

  </div>
</div>
